[package]
name = "spl-associated-token-account-mollusk-harness"
version = "1.0.0"
description = "SPL Associated Token Account Mollusk Testing Harness"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/solana-program/associated-token-account"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
mollusk-svm = { version = "0.7.1" }
mollusk-svm-programs-token = { version = "0.7.1" }
solana-account = "3.2"
solana-instruction = "3.1"
solana-keypair = "3.0"
solana-program-error = "3.0"
solana-program-option = "3.0"
solana-program-pack = "3.0"
solana-pubkey = "3.0"
solana-rent = "3.0"
solana-signer = "3.0"
solana-system-interface = { version = "2.0", features = ["bincode"] }
solana-sysvar = "3.0"
spl-associated-token-account-interface = "2.0"
spl-token-interface = "2.0"
spl-token-2022-interface = "2.1"
